root = "."
tmp_dir = ".air"

[build]
  bin = "./.air/memos.exe"
  cmd = "go build -o ./.air/memos.exe ./main.go"
  delay = 1000
  exclude_dir = [".air", "web", "build"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  send_interrupt = true
  kill_delay = 2000
