name: build-and-push-release-image

on:
  push:
    branches:
      # Run on pushing branches like `release/1.0.0`
      - "release/v*.*.*"

jobs:
  build-and-push-release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract build args
        # Extract version from branch name
        # Example: branch name `release/v1.0.0` sets up env.VERSION=1.0.0
        run: |
          echo "VERSION=${GITHUB_REF_NAME#release/v}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: neosmemo
          password: ${{ secrets.DOCKER_NEOSMEMO_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: neosmemo/memos:${{ env.VERSION }}
